
VAGRANTFILE_API_VERSION = "2"

################################################################################
# check plugins
################################################################################
required_plugins = %w(vagrant-hostmanager vagrant-hosts vagrant-vbguest)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

################################################################################
# Global settings
################################################################################
  env = 'single'
  ram = 2048

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box              = 'puppetlabs/centos-7.2-64-puppet'
  config.vm.box_check_update = true
  config.ssh.insert_key      = false

################################################################################
# Virtualbox(es)
################################################################################

  config.vm.provider :virtualbox do |vb|
    vb.name  = "#{env}.neo4j.vagrant"
    vb.customize [
      'modifyvm', :id,
      '--groups', '/Demo',
      '--memory', "#{ram}",
      '--cpus', 2
    ]
  end

  ### 
  ### Networking
  ###
  config.vm.host_name = "#{env}.neo4j.vagrant"
  config.vm.network :private_network, ip: '10.10.10.10'
  # http port
  config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 7474, host: 7474
  # https port
  config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 7473, host: 7473

  ### 
  ### Synced directories
  ### 
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder '../../puppet/hiera', '/var/lib/hiera'
  config.vm.synced_folder '../../puppet/manifests', "/etc/puppet/environments/#{env}/manifests"
  config.vm.synced_folder '../../puppet/modules', "/etc/puppet/environments/#{env}/modules"

  ### 
  ### Puppet provisioning
  ### 
 config.vm.provision :puppet do |puppet|
    puppet.options           = "--debug --verbose"
    puppet.environment_path  = "../../puppet/environments"
    puppet.environment       = "#{env}"
    puppet.hiera_config_path = "../../puppet/hiera.yaml"
  end
end
