
VAGRANTFILE_API_VERSION = "2"

################################################################################
# check plugins
################################################################################
required_plugins = %w(vagrant-hostmanager vagrant-cachier vagrant-puppet-install)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

################################################################################
# Global settings
################################################################################
  env = 'single'
  ip  = '10.10.10.10'
  ram = 2048

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.hostmanager.enabled           = true
  config.hostmanager.manage_host       = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline   = true

  config.vm.box                        = 'bento/centos-7.3'
  config.vm.box_check_update           = false
  config.ssh.insert_key                = false

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :machine
  end

  if Vagrant.has_plugin?('vagrant-puppet-install')
    config.puppet_install.puppet_version = :latest
  end

################################################################################
# Virtualbox(es)
################################################################################

  config.vm.provider :virtualbox do |vb|
    vb.name  = "neo4j.#{env}.vagrant"
    vb.customize [
      'modifyvm', :id,
      '--groups', '/Demo',
      '--memory', "#{ram}",
      '--cpus', 1
    ]
  end

  #-----------------------------------------------------------------------------
  #-- Synced directories
  #-----------------------------------------------------------------------------
  config.vm.synced_folder ".", "/vagrant", disabled: true
  dirs = %w(hieradata manifests)
  dirs.each { |dir|
    config.vm.synced_folder "../../puppet/#{env}/#{dir}", "/etc/puppetlabs/code/environments/#{env}/#{dir}",
	:owner => 'root',
	:group => 'root'
  }
  config.vm.synced_folder "../../puppet/modules", "/etc/puppetlabs/code/modules",
 	:owner => 'root',
	:group => 'root'

  #-----------------------------------------------------------------------------
  #-- Networking
  #-----------------------------------------------------------------------------
  # http port
  config.vm.network :forwarded_port, host_ip: "#{ip}", guest: 7474, host: 7474
  # https port
  config.vm.network :forwarded_port, host_ip: "#{ip}", guest: 7473, host: 7473
  # bolt port
  config.vm.network :forwarded_port, host_ip: "#{ip}", guest: 9000, host: 9000  

  #-----------------------------------------------------------------------------
  #-- define node
  #-----------------------------------------------------------------------------
  config.vm.define :neo4j do |node|
    node.vm.hostname         = "neo4j.#{env}.vagrant"
    node.hostmanager.aliases = %w(neo4j.localdomain neo4j)
    node.vm.network :private_network, ip: "#{ip}"
  end

  #-----------------------------------------------------------------------------
  #-- Puppet provisioning
  #-----------------------------------------------------------------------------
  config.vm.provision :puppet do |puppet|
    puppet.options           = "--debug --verbose"
    puppet.environment_path  = "../../puppet"
    puppet.environment       = "#{env}"
    puppet.hiera_config_path = "../../puppet/hiera.yaml"
  end
end
