
VAGRANTFILE_API_VERSION = "2"

require 'yaml'

################################################################################
# check plugins
################################################################################
required_plugins = %w(vagrant-hostmanager vagrant-cachier vagrant-vbguest)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

################################################################################
# read YAML file with server and box details
################################################################################
nodes = YAML.load_file('config/nodes.yaml')

################################################################################
# Global settings
################################################################################
  env = 'ha'
  ram = 2048

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.hostmanager.enabled           = true
  config.hostmanager.manage_host       = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline   = true

  config.vm.box                        = 'centos-72-x86_64'
  config.vm.box_check_update           = true
  config.ssh.insert_key                = false

  config.vbguest.auto_update           = true

################################################################################
# Caching
################################################################################
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_ooptions: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

################################################################################
# Virtualbox(es)
################################################################################

  ### 
  ### Synced directories
  ### 
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../puppet/hiera", "/var/lib/hiera"
  config.vm.synced_folder "../../puppet/manifests", "/etc/puppet/environments/#{env}/manifests"
  config.vm.synced_folder "../../puppet/modules", "/etc/puppet/environments/#{env}/modules"

  nodes.each do |srv|

    config.vm.define srv["name"] do |node|
      node.vm.hostname         = srv["name"] + ".#{env}.vagrant"

      node.vm.provider :virtualbox do |vb|
        vb.name  = srv["name"] + ".#{env}.vagrant"
        vb.customize [
          'modifyvm', :id,
          '--groups', '/Demo',
          '--memory', srv["ram"],
          '--cpus', srv["cpus"]
        ]
      end
  
      ### Networking
      node.vm.network :private_network, ip: srv["ip"]
      srv["ports"].each do |port|
        node.vm.network :forwarded_port, host_ip: "127.0.0.1", guest: port["guest"], host: port["host"]
      end

      ### Puppet provisioning
      node.vm.provision :puppet do |puppet|
        puppet.options           = "--debug --verbose"
        puppet.environment_path  = "../../puppet/environments"
        puppet.environment       = "#{env}"
        puppet.hiera_config_path = "../../puppet/hiera.yaml"
      end
    end
  end
end
